#! /bin/zsh
# Filza da kullanmak için, Terminali normal (nonSuperuser) olarak #ayarlayın.
#=====================# Renklendirme :)
Y='\033[1;33m' #=Sarı=# 
#=====================# 
#Determine device 
test=$(uname -m)
if [[ $test == x86_64 ]]; then
	clear
echo "Updating Repo(s)"

cd /Users/turannul/Documents/GitHub.nosync/home
git pull
git add /Users/turannul/Documents/GitHub.nosync/home
cd /Users/turannul/Documents/GitHub.nosync/repo
git pull
git add /Users/turannul/Documents/GitHub.nosync/repo

echo "Updated"

clear

echo "Commit changes"

cd /Users/turannul/Documents/GitHub.nosync/repo
git commit -a -m "Updated."
cd /Users/turannul/Documents/GitHub.nosync/home
git commit -a -m "Updated."

echo "Comitted."

clear

echo "${Y}Upload started."

cd /Users/turannul/Documents/GitHub.nosync/repo
git push
cd /Users/turannul/Documents/GitHub.nosync/home
git push 

echo "Upload Completed"

clear 

tput setaf 2;echo "Success | macOS"

else
	
clear
echo "Updating Repo(s)"

cd /private/var/mobile/Documents/Github/home
git pull
git add /private/var/mobile/Documents/Github/home
cd /private/var/mobile/Documents/Github/repo
git pull
git add /private/var/mobile/Documents/Github/repo

echo "Updated"

clear

echo "Commit changes"

cd /private/var/mobile/Documents/Github/repo
git commit -a -m "Updated."
cd /private/var/mobile/Documents/Github/home
git commit -a -m "Updated."

echo "Comitted."

clear

echo "${Y}Upload started."

cd /private/var/mobile/Documents/Github/repo
git push
cd /private/var/mobile/Documents/Github/home
git push 

echo "Upload Completed"

clear 

tput setaf 2;echo "Success | iOS"

fi
